contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false

baseurl = "/"
canonifyurls = true

ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$" ]

googleAnalytics = ""
disqusShortname = ""

pygmentsuseclasses = true

[permalinks]
	post = ":year/:month/:day/:slug/"
	fixed = ":title/"

[params]
	Title = ""
	Tagline = ""
	Author = ""
	Blurb = ""
	DateForm = "Jan 2 2006"
	MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
	MathJaxVersion = "2.7.5"
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = [ "r" ]
  highlightjsTheme = "github"
